version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  assignees:
  - Nic-Grunklee
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.11.20
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
    - 5.12.6
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: config
    versions:
    - 3.3.3
    - 3.3.4
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
